<?php
declare(strict_types=1);

/**
 * @file classes/plugins/GenericPlugin.inc.php
 *
 * Copyright (c) 2013-2019 Simon Fraser University
 * Copyright (c) 2000-2019 John Willinsky
 * Distributed under the GNU GPL v2. For full terms see the file docs/COPYING.
 *
 * @class GenericPlugin
 * @ingroup plugins
 *
 * @brief Abstract class for generic plugins
 * * MODERNIZED FOR PHP 7.4+ (Wizdam FORK)
 * - Constructor updated to __construct
 * - Parent constructor call updated to parent::__construct
 * - Removed reference operators (&)
 */

import('lib.wizdam.classes.plugins.LazyLoadPlugin');

class GenericPlugin extends LazyLoadPlugin {
    
    /**
     * Constructor
     */
    public function __construct() {
        parent::__construct();
    }

    /*
     * Override protected methods from PKPPlugin
     */

    /**
     * Generic plug-ins implement the enabled/disabled logic
     * by default. This is necessary so that we can make sure
     * that disabled plug-ins will not have to be instantiated.
     * Call this method with a list of management verbs (if any)
     * generated by the custom plug-in.
     * @see PKPPlugin::getManagementVerbs()
	 * @param array $verbs
	 * @param mixed $request
     * @return array()
     */
    public function getManagementVerbs(array $verbs = [], $request = null): array {
        // Site plug-ins can only be administered by site admins
        if ($this->isSitePlugin() && !Validation::isSiteAdmin()) {
            return [];
        }
    
        // Tambahkan enable/disable di sini
        if ($this->getEnabled($request)) {
            $verbs[] = array('disable', __('manager.plugins.disable'));
        } else {
            $verbs[] = array('enable', __('manager.plugins.enable'));
        }
    
        // Teruskan $verbs dan $request ke parent dengan benar
        return parent::getManagementVerbs($verbs, $request);
    }

    /**
	 * Handle management actions. This method is called when a management verb is triggered.
     * @see PKPPlugin::manage()
     * Modernized for PHP 7.4/8.x compatibility
     * @param string $verb
     * @param array $args
     * @param string $message (Passed by reference)
     * @param array $messageParams (Passed by reference)
     * @param mixed $request
     * @return bool
     */
    public function manage(string $verb, array $args, string $message, array $messageParams, $request = null): bool {
        if ($verb === 'enable') {
            $this->setEnabled(true, $request);
            return false; // false = redirect ke halaman plugin list
        }
    
        if ($verb === 'disable') {
            $this->setEnabled(false, $request);
            return false; // false = redirect ke halaman plugin list
        }
    
        // Untuk verb lain, cek dulu apakah plugin enabled
        if (!$this->getEnabled($request)) {
            fatalError('Invalid management action on disabled plug-in!');
        }
    
        return true;
    }
}
?>